# Generated by Django 5.2.2 on 2025-06-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='delivery_time',
            field=models.IntegerField(help_text='Tempo de entrega em dias'),
        ),
    ]
