# Generated by Django 5.2.2 on 2025-06-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanic', '0004_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
    ]
