# Generated by Django 5.2.2 on 2025-06-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanic', '0005_alter_product_name_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delivery_time_unit',
            field=models.CharField(choices=[('min', 'Minuto'), ('h', 'Hora'), ('d', 'Dia')], default='hj', max_length=10, verbose_name='Unidade de Tempo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery_time',
            field=models.CharField(max_length=25, verbose_name='Tempo de Entrega'),
        ),
    ]
