# Generated by Django 5.2.2 on 2025-06-06 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanic', '0006_service_delivery_time_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery_time',
            field=models.IntegerField(verbose_name='Tempo de Entrega'),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery_time_unit',
            field=models.CharField(choices=[('min', 'Minutos'), ('h', 'Horas'), ('d', 'Dias')], default='hj', help_text='Tempo de entrega  em Minutos, Horas ou Dias', max_length=10, verbose_name='Unidade de Tempo'),
        ),
    ]
