# Generated by Django 5.2.2 on 2025-06-11 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanic', '0007_customer_created_at_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mecanic.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo de Entrega'),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery_time_unit',
            field=models.CharField(blank=True, choices=[('min', 'Minutos'), ('h', 'Horas'), ('d', 'Dias')], default='hj', help_text='Tempo de entrega  em Minutos, Horas ou Dias', max_length=10, verbose_name='Unidade de Tempo'),
        ),
    ]
